# Generated by Django 4.0.4 on 2022-06-15 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='食材名')),
                ('content', models.TextField(blank=True, max_length=400, null=True, verbose_name='食材説明')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='食材価格')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='メニュー名')),
                ('content', models.TextField(blank=True, max_length=400, null=True, verbose_name='メニュー説明')),
                ('food_number1', models.IntegerField(blank=True, null=True, verbose_name='食材1の個数')),
                ('food_number2', models.IntegerField(blank=True, null=True, verbose_name='食材2の個数')),
                ('food_number3', models.IntegerField(blank=True, null=True, verbose_name='食材3の個数')),
                ('food_number4', models.IntegerField(blank=True, null=True, verbose_name='食材4の個数')),
                ('food_number5', models.IntegerField(blank=True, null=True, verbose_name='食材5の個数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('food_id1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_food_id1', to='api.food', verbose_name='食材1のid')),
                ('food_id2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_food_id2', to='api.food', verbose_name='食材2のid')),
                ('food_id3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_food_id3', to='api.food', verbose_name='食材3のid')),
                ('food_id4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_food_id4', to='api.food', verbose_name='食材4のid')),
                ('food_id5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_food_id5', to='api.food', verbose_name='食材5のid')),
            ],
        ),
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=400, null=True, verbose_name='計算タイトル')),
                ('cost', models.IntegerField(verbose_name='計算金額')),
                ('food_number1', models.IntegerField(blank=True, null=True, verbose_name='食材1の個数')),
                ('food_number2', models.IntegerField(blank=True, null=True, verbose_name='食材2の個数')),
                ('food_number3', models.IntegerField(blank=True, null=True, verbose_name='食材3の個数')),
                ('food_number4', models.IntegerField(blank=True, null=True, verbose_name='食材4の個数')),
                ('food_number5', models.IntegerField(blank=True, null=True, verbose_name='食材5の個数')),
                ('food_number6', models.IntegerField(blank=True, null=True, verbose_name='食材6の個数')),
                ('food_number7', models.IntegerField(blank=True, null=True, verbose_name='食材7の個数')),
                ('food_number8', models.IntegerField(blank=True, null=True, verbose_name='食材8の個数')),
                ('food_number9', models.IntegerField(blank=True, null=True, verbose_name='食材9の個数')),
                ('food_number10', models.IntegerField(blank=True, null=True, verbose_name='食材10の個数')),
                ('food_number11', models.IntegerField(blank=True, null=True, verbose_name='食材11の個数')),
                ('food_number12', models.IntegerField(blank=True, null=True, verbose_name='食材12の個数')),
                ('food_number13', models.IntegerField(blank=True, null=True, verbose_name='食材13の個数')),
                ('food_number14', models.IntegerField(blank=True, null=True, verbose_name='食材14の個数')),
                ('food_number15', models.IntegerField(blank=True, null=True, verbose_name='食材15の個数')),
                ('food_number16', models.IntegerField(blank=True, null=True, verbose_name='食材16の個数')),
                ('food_number17', models.IntegerField(blank=True, null=True, verbose_name='食材17の個数')),
                ('food_number18', models.IntegerField(blank=True, null=True, verbose_name='食材18の個数')),
                ('food_number19', models.IntegerField(blank=True, null=True, verbose_name='食材19の個数')),
                ('food_number20', models.IntegerField(blank=True, null=True, verbose_name='食材20の個数')),
                ('food_number21', models.IntegerField(blank=True, null=True, verbose_name='食材21の個数')),
                ('food_number22', models.IntegerField(blank=True, null=True, verbose_name='食材22の個数')),
                ('food_number23', models.IntegerField(blank=True, null=True, verbose_name='食材23の個数')),
                ('food_number24', models.IntegerField(blank=True, null=True, verbose_name='食材24の個数')),
                ('food_number25', models.IntegerField(blank=True, null=True, verbose_name='食材25の個数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('food_id1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id1', to='api.food', verbose_name='食材1のid')),
                ('food_id10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id10', to='api.food', verbose_name='食材10のid')),
                ('food_id11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id11', to='api.food', verbose_name='食材11のid')),
                ('food_id12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id12', to='api.food', verbose_name='食材12のid')),
                ('food_id13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id13', to='api.food', verbose_name='食材13のid')),
                ('food_id14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id14', to='api.food', verbose_name='食材14のid')),
                ('food_id15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id15', to='api.food', verbose_name='食材15のid')),
                ('food_id16', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id16', to='api.food', verbose_name='食材16のid')),
                ('food_id17', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id17', to='api.food', verbose_name='食材17のid')),
                ('food_id18', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id18', to='api.food', verbose_name='食材18のid')),
                ('food_id19', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id19', to='api.food', verbose_name='食材19のid')),
                ('food_id2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id2', to='api.food', verbose_name='食材2のid')),
                ('food_id20', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id20', to='api.food', verbose_name='食材20のid')),
                ('food_id21', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id21', to='api.food', verbose_name='食材21のid')),
                ('food_id22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id22', to='api.food', verbose_name='食材22のid')),
                ('food_id23', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id23', to='api.food', verbose_name='食材23のid')),
                ('food_id24', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id24', to='api.food', verbose_name='食材24のid')),
                ('food_id25', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id25', to='api.food', verbose_name='食材25のid')),
                ('food_id3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id3', to='api.food', verbose_name='食材3のid')),
                ('food_id4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id4', to='api.food', verbose_name='食材4のid')),
                ('food_id5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id5', to='api.food', verbose_name='食材5のid')),
                ('food_id6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id6', to='api.food', verbose_name='食材6のid')),
                ('food_id7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id7', to='api.food', verbose_name='食材7のid')),
                ('food_id8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id8', to='api.food', verbose_name='食材8のid')),
                ('food_id9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_food_id9', to='api.food', verbose_name='食材9のid')),
                ('menu_id1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_menu_id1', to='api.menu', verbose_name='メニュー1のid')),
                ('menu_id2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_menu_id2', to='api.menu', verbose_name='メニュー2のid')),
                ('menu_id3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_menu_id3', to='api.menu', verbose_name='メニュー3のid')),
                ('menu_id4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_menu_id4', to='api.menu', verbose_name='メニュー4のid')),
                ('menu_id5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_menu_id5', to='api.menu', verbose_name='メニュー5のid')),
            ],
        ),
    ]
