from django.db import models
from django.utils import timezone # timezoneのインポート

class Food(models.Model):
    name = models.CharField(verbose_name='食材名', max_length=40)
    content = models.TextField(verbose_name='食材説明', max_length=400, blank=True, null=True)
    cost = models.IntegerField(verbose_name='食材価格', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)
    def __str__(self):
        return self.name

class Menu(models.Model):
    name = models.CharField(verbose_name='メニュー名', max_length=40)
    content = models.TextField(verbose_name='メニュー説明', max_length=400, blank=True, null=True)
    food_id1 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材1のid', related_name='menu_food_id1', blank=True, null=True)
    food_number1 = models.IntegerField(verbose_name='食材1の個数', blank=True, null=True)
    food_id2 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材2のid', related_name='menu_food_id2', blank=True, null=True)
    food_number2 = models.IntegerField(verbose_name='食材2の個数', blank=True, null=True)
    food_id3 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材3のid', related_name='menu_food_id3', blank=True, null=True)
    food_number3 = models.IntegerField(verbose_name='食材3の個数', blank=True, null=True)
    food_id4 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材4のid', related_name='menu_food_id4', blank=True, null=True)
    food_number4 = models.IntegerField(verbose_name='食材4の個数', blank=True, null=True)
    food_id5 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材5のid', related_name='menu_food_id5', blank=True, null=True)
    food_number5 = models.IntegerField(verbose_name='食材5の個数', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)
    def __str__(self):
        return self.name

class Calc(models.Model):
    title = models.TextField(verbose_name='計算タイトル', max_length=400, blank=True, null=True)
    cost = models.IntegerField(verbose_name='計算金額')
    menu_id1 = models.ForeignKey(Menu, on_delete=models.CASCADE, verbose_name='メニュー1のid', related_name='calc_menu_id1', blank=True, null=True)
    menu_id2 = models.ForeignKey(Menu, on_delete=models.CASCADE, verbose_name='メニュー2のid', related_name='calc_menu_id2', blank=True, null=True)
    menu_id3 = models.ForeignKey(Menu, on_delete=models.CASCADE, verbose_name='メニュー3のid', related_name='calc_menu_id3', blank=True, null=True)
    menu_id4 = models.ForeignKey(Menu, on_delete=models.CASCADE, verbose_name='メニュー4のid', related_name='calc_menu_id4', blank=True, null=True)
    menu_id5 = models.ForeignKey(Menu, on_delete=models.CASCADE, verbose_name='メニュー5のid', related_name='calc_menu_id5', blank=True, null=True)
    food_id1 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材1のid', related_name='calc_food_id1', blank=True, null=True)
    food_number1 = models.IntegerField(verbose_name='食材1の個数', blank=True, null=True)
    food_id2 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材2のid', related_name='calc_food_id2', blank=True, null=True)
    food_number2 = models.IntegerField(verbose_name='食材2の個数', blank=True, null=True)
    food_id3 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材3のid', related_name='calc_food_id3', blank=True, null=True)
    food_number3 = models.IntegerField(verbose_name='食材3の個数', blank=True, null=True)
    food_id4 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材4のid', related_name='calc_food_id4', blank=True, null=True)
    food_number4 = models.IntegerField(verbose_name='食材4の個数', blank=True, null=True)
    food_id5 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材5のid', related_name='calc_food_id5', blank=True, null=True)
    food_number5 = models.IntegerField(verbose_name='食材5の個数', blank=True, null=True)
    food_id6 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材6のid', related_name='calc_food_id6', blank=True, null=True)
    food_number6 = models.IntegerField(verbose_name='食材6の個数', blank=True, null=True)
    food_id7 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材7のid', related_name='calc_food_id7', blank=True, null=True)
    food_number7 = models.IntegerField(verbose_name='食材7の個数', blank=True, null=True)
    food_id8 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材8のid', related_name='calc_food_id8', blank=True, null=True)
    food_number8 = models.IntegerField(verbose_name='食材8の個数', blank=True, null=True)
    food_id9 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材9のid', related_name='calc_food_id9', blank=True, null=True)
    food_number9 = models.IntegerField(verbose_name='食材9の個数', blank=True, null=True)
    food_id10 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材10のid', related_name='calc_food_id10', blank=True, null=True)
    food_number10 = models.IntegerField(verbose_name='食材10の個数', blank=True, null=True)
    food_id11 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材11のid', related_name='calc_food_id11', blank=True, null=True)
    food_number11 = models.IntegerField(verbose_name='食材11の個数', blank=True, null=True)
    food_id12 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材12のid', related_name='calc_food_id12', blank=True, null=True)
    food_number12 = models.IntegerField(verbose_name='食材12の個数', blank=True, null=True)
    food_id13 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材13のid', related_name='calc_food_id13', blank=True, null=True)
    food_number13 = models.IntegerField(verbose_name='食材13の個数', blank=True, null=True)
    food_id14 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材14のid', related_name='calc_food_id14', blank=True, null=True)
    food_number14 = models.IntegerField(verbose_name='食材14の個数', blank=True, null=True)
    food_id15 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材15のid', related_name='calc_food_id15', blank=True, null=True)
    food_number15 = models.IntegerField(verbose_name='食材15の個数', blank=True, null=True)
    food_id16 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材16のid', related_name='calc_food_id16', blank=True, null=True)
    food_number16 = models.IntegerField(verbose_name='食材16の個数', blank=True, null=True)
    food_id17 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材17のid', related_name='calc_food_id17', blank=True, null=True)
    food_number17 = models.IntegerField(verbose_name='食材17の個数', blank=True, null=True)
    food_id18 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材18のid', related_name='calc_food_id18', blank=True, null=True)
    food_number18 = models.IntegerField(verbose_name='食材18の個数', blank=True, null=True)
    food_id19 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材19のid', related_name='calc_food_id19', blank=True, null=True)
    food_number19 = models.IntegerField(verbose_name='食材19の個数', blank=True, null=True)
    food_id20 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材20のid', related_name='calc_food_id20', blank=True, null=True)
    food_number20 = models.IntegerField(verbose_name='食材20の個数', blank=True, null=True)
    food_id21 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材21のid', related_name='calc_food_id21', blank=True, null=True)
    food_number21 = models.IntegerField(verbose_name='食材21の個数', blank=True, null=True)
    food_id22 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材22のid', related_name='calc_food_id22', blank=True, null=True)
    food_number22 = models.IntegerField(verbose_name='食材22の個数', blank=True, null=True)
    food_id23 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材23のid', related_name='calc_food_id23', blank=True, null=True)
    food_number23 = models.IntegerField(verbose_name='食材23の個数', blank=True, null=True)
    food_id24 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材24のid', related_name='calc_food_id24', blank=True, null=True)
    food_number24 = models.IntegerField(verbose_name='食材24の個数', blank=True, null=True)
    food_id25 = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name='食材25のid', related_name='calc_food_id25', blank=True, null=True)
    food_number25 = models.IntegerField(verbose_name='食材25の個数', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)
    def __str__(self):
        return self.name